#!/usr/bin/env python3
"""SOC 2 daily evidence-completeness check.

For each CC criterion in the plan, verify last-30-days has at least one
evidence event in collected/. Flags missing criteria + writes a forward
event to hydra/audit-trail (if present) as `soc2-evidence-gap`.

Updates auditor-readiness-dashboard.md in place.

Stdlib only. Idempotent: re-running on the same day overwrites the dashboard.
"""
from __future__ import annotations

import json
import sys
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
EVIDENCE_DIR = ROOT / "agent-foundations" / "compliance" / "soc2-evidence"
COLLECTED = EVIDENCE_DIR / "collected"
DASHBOARD = EVIDENCE_DIR / "auditor-readiness-dashboard.md"

CRITERIA = [
    "CC1.1", "CC1.2", "CC1.3", "CC1.4", "CC1.5",
    "CC2.1", "CC2.2", "CC2.3",
    "CC3.1", "CC3.2", "CC3.3", "CC3.4",
    "CC4.1", "CC4.2",
    "CC5.1", "CC5.2", "CC5.3",
    "CC6.1", "CC6.2", "CC6.3", "CC6.4", "CC6.5", "CC6.6", "CC6.7", "CC6.8",
    "CC7.1", "CC7.2", "CC7.3", "CC7.4", "CC7.5",
    "CC8.1",
    "CC9.1", "CC9.2",
    "A1.1", "A1.2", "A1.3",
]

NA_CRITERIA = {"CC6.4", "CC6.5"}  # physical access not applicable
SPARSE_CRITERIA = {"CC1.2", "A1.3"}  # GAPs per soc2.md — monthly attestation only


def today() -> datetime:
    return datetime.now(timezone.utc)


def count_events_in_window(criterion: str, days: int = 30) -> tuple[int, int]:
    """Return (total_events, days_with_events) in the last `days` days."""
    if not COLLECTED.exists():
        return 0, 0
    cutoff = today() - timedelta(days=days)
    total = 0
    days_seen: set[str] = set()
    for day_dir in COLLECTED.iterdir():
        if not day_dir.is_dir():
            continue
        try:
            d = datetime.strptime(day_dir.name, "%Y-%m-%d").replace(tzinfo=timezone.utc)
        except ValueError:
            continue
        if d < cutoff:
            continue
        f = day_dir / f"{criterion}.jsonl"
        if not f.exists():
            continue
        try:
            n = sum(1 for line in f.read_text(encoding="utf-8").splitlines() if line.strip())
        except OSError:
            n = 0
        if n > 0:
            total += n
            days_seen.add(day_dir.name)
    return total, len(days_seen)


def status_for(criterion: str, total: int, days_seen: int) -> str:
    if criterion in NA_CRITERIA:
        return "N/A" if total > 0 else "N/A-no-event"
    floor = 1 if criterion in SPARSE_CRITERIA else 1
    if total >= floor and days_seen >= 1:
        return "OK"
    return "MISSING"


def coverage_pct(rows: list[tuple]) -> float:
    applicable = [r for r in rows if r[0] not in NA_CRITERIA]
    if not applicable:
        return 0.0
    ok = sum(1 for r in applicable if r[3] == "OK")
    return round(100 * ok / len(applicable), 1)


def forward_to_audit_trail(gaps: list[str]) -> None:
    """Best-effort: append a soc2-evidence-gap event to hydra/audit-trail if present."""
    log = ROOT / "hydra" / "plugins" / "audit-trail" / "state" / "log.jsonl"
    if not log.parent.exists():
        return
    ev = {
        "ts": today().strftime("%Y-%m-%dT%H:%M:%SZ"),
        "source": "soc2-evidence/evidence-completeness-check",
        "event_type": "soc2-evidence-gap",
        "gaps": gaps,
    }
    try:
        with log.open("a", encoding="utf-8") as f:
            f.write(json.dumps(ev, separators=(",", ":")) + "\n")
    except OSError:
        pass


def render_dashboard(rows: list[tuple], pct: float, gaps: list[str]) -> str:
    lines = []
    lines.append("# SOC 2 Auditor-Readiness Dashboard")
    lines.append("")
    lines.append(f"**Generated:** {today().strftime('%Y-%m-%d %H:%M UTC')}")
    lines.append(f"**Window:** last 30 days")
    lines.append(f"**Coverage (applicable criteria):** {pct}%")
    lines.append("")
    lines.append("Source-of-truth: this file is regenerated by `scripts/evidence-completeness-check.py`. ")
    lines.append("Do NOT hand-edit — your edits are overwritten on the next run.")
    lines.append("")
    lines.append("## Per-criterion coverage")
    lines.append("")
    lines.append("| Criterion | Events (30d) | Days with events | Status | Notes |")
    lines.append("|---|---:|---:|---|---|")
    for crit, total, days_seen, status in rows:
        notes = ""
        if crit in NA_CRITERIA:
            notes = "physical-not-applicable"
        elif crit in SPARSE_CRITERIA:
            notes = "GAP per soc2.md; monthly attestation"
        lines.append(f"| {crit} | {total} | {days_seen} | {status} | {notes} |")
    lines.append("")
    if gaps:
        lines.append("## Open gaps (MISSING criteria)")
        lines.append("")
        for g in gaps:
            lines.append(f"- {g}")
    else:
        lines.append("## Open gaps")
        lines.append("")
        lines.append("None. All applicable criteria have at least one event in the last 30 days.")
    lines.append("")
    lines.append("## Operator weekly review")
    lines.append("")
    lines.append("1. Open this file every Monday.")
    lines.append("2. For each MISSING row, open the corresponding `playbooks/<criterion>.md` and follow the escalation path.")
    lines.append("3. For sparse criteria (CC1.2, A1.3), confirm at least one attestation event in the last 30 days.")
    lines.append("4. If coverage drops below 95%, surface to the security-closure synthesis queue.")
    lines.append("")
    return "\n".join(lines) + "\n"


def main() -> int:
    rows: list[tuple] = []
    for crit in CRITERIA:
        total, days_seen = count_events_in_window(crit)
        status = status_for(crit, total, days_seen)
        rows.append((crit, total, days_seen, status))
    pct = coverage_pct(rows)
    gaps = [r[0] for r in rows if r[3] == "MISSING"]
    DASHBOARD.write_text(render_dashboard(rows, pct, gaps), encoding="utf-8")
    if gaps:
        forward_to_audit_trail(gaps)
    summary = {"coverage_pct": pct, "gap_count": len(gaps), "gaps": gaps,
               "total_criteria": len(rows), "na_count": len(NA_CRITERIA)}
    print(json.dumps(summary, indent=2))
    return 0 if pct >= 95.0 or not gaps else 1


if __name__ == "__main__":
    sys.exit(main())
